base:
    is_dev : true
    serial_number : 1.0.0
    service_name : gmsec
    service_displayname : gmsecserver
    sercice_desc : gmsec微服务
mysql_info:
    host : localhost
    port : 3306
    username : root
    password : 123456
    database : oauth_db

